# Generated by Django 5.1.1 on 2024-09-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bautizo',
            name='fecha_bautizo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
