# Generated by Django 5.1.1 on 2024-09-21 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_bautizo_madre_alter_bautizo_nombremadrina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bautizo',
            name='fecha_bautizo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='lugar_nacimiento',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='madre',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='nacimientolugarmadre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='nacimientolugarpadre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='nombremadrina',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='nombrepadrino',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='oficiante',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='padre',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='padrinos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
