# Generated by Django 5.1.1 on 2024-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_bautizo_fecha_bautizo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='priComunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('parroquia', models.CharField(default="'La Purisima' - Concepción", max_length=255)),
                ('fecha', models.DateField()),
                ('padre', models.CharField(max_length=80)),
                ('madre', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='padrinos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='padrinos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
