# Generated by Django 5.1.1 on 2024-09-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_pricomunion_alter_confirmacion_padrinos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacion',
            name='padres',
            field=models.CharField(max_length=150),
        ),
    ]
