# Generated by Django 5.1.1 on 2024-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_confirmacion_padres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bautizo',
            name='nombremadrina',
        ),
        migrations.RemoveField(
            model_name='bautizo',
            name='nombrepadrino',
        ),
        migrations.AddField(
            model_name='bautizo',
            name='padrinos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
