# Generated by Django 5.1.1 on 2024-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_bautizo_nombremadrina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bautizo',
            name='anotaciones',
            field=models.CharField(default='Ninguno', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='anotaciones',
            field=models.CharField(default='Ninguno', max_length=255),
        ),
    ]
