# Generated by Django 5.1.1 on 2024-09-28 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_bautizo_anotaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacion',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='nombres',
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
